In [1]:
import geopandas as gpd
import pandas as pd
import geopandas
import shapely.geometry as geom
from polygon_geohasher.polygon_geohasher import polygon_to_geohashes, geohashes_to_polygon
import pygeohash as gh
%matplotlib inline
import geohash
import geopandas as gp
import pandas as pd
import math
import geojson
from geojson import MultiLineString
from shapely.geometry import MultiLineString
from shapely.geometry import MultiPoint
import numpy as np
from shapely import geometry
from shapely.geometry import Point, Polygon, box,LineString
from geopandas import datasets, GeoDataFrame, read_file
from geopandas.tools import overlay
from matplotlib import pyplot
import matplotlib.pyplot as plt
from shapely.geometry.polygon import LinearRing, Polygon
from numpy import cos,sin,arccos
import numpy as np
from pylab import *
from shapely.ops import cascaded_union
from shapely.geometry import Point, LineString, mapping
import scipy.interpolate
import geopy
import geopy.distance
import time
import networkx as nx
from sklearn.model_selection import train_test_split
import datetime as dt

In [74]:
apr_weather = pd.read_csv('APR_SG_hourly_weather.csv')
sg_geofabrik = pd.read_csv('sg_geofabrik.csv')
apr_weather['date'] = pd.to_datetime(apr_weather['date'], format='%Y%m%d')
apr_weather['day'] = apr_weather['date'].dt.day
apr_weather['time'] = apr_weather['time'].astype(str)
apr_weather[['hour','minute']] = apr_weather['time'].str.split(':',expand=True)
apr_weather['hour'] = apr_weather['hour'].astype(int)

In [75]:
apr_weather.head()

        date  time                  weather_string   rain  day  hour minute
0 2019-04-01  1:00                 passing clouds.  False    1     1     00
1 2019-04-01  2:00  thundershowers. partly cloudy.   True    1     2     00
2 2019-04-01  3:00  thunderstorms. passing clouds.   True    1     3     00
3 2019-04-01  4:00  thunderstorms. passing clouds.   True    1     4     00
4 2019-04-01  5:00  thunderstorms. passing clouds.   True    1     5     00

In [76]:
apr_weather.loc[(apr_weather['day'] == 1)& (apr_weather['hour'] == 2)]

        date  time                  weather_string  rain  day  hour minute
1 2019-04-01  2:00  thundershowers. partly cloudy.  True    1     2     00

In [86]:
sg_geofabrik.head()

   geohash  no_poi  maxspeed
0  w21xjfc     1.0      70.0
1  w21xjzu     1.0       NaN
2  w21xnyn     3.0       NaN
3  w21xpnd     1.0       NaN
4  w21xpye     1.0       NaN

In [102]:
sg_geofabrik.loc[sg_geofabrik['geohash'] == 'w21xjfc']['no_poi']
sg_geofabrik.loc[sg_geofabrik['geohash'] == 'w21xjfc']['maxspeed']
print(len(sg_geofabrik.loc[sg_geofabrik['geohash'] == 'w21xjfc']['no_poi']))

1

In [101]:
sg_geofabrik.loc[sg_geofabrik['geohash'] == 'w21z6h']['no_poi']
print(len(sg_geofabrik.loc[sg_geofabrik['geohash'] == 'w21z6h']['no_poi']))

0

In [92]:
print(sg_geofabrik['no_poi'].mean())
print(sg_geofabrik['maxspeed'].mean())

5.139851485148514
52.24763332388013

In [33]:
weekend_busy_G = nx.Graph()
weekend_busy = pd.read_csv('processed_csv/weekend_geohash_busy_6.csv')
weekend_busy = weekend_busy.groupby('node_trip').max().reset_index()
weekend_busy[['source', 'dest']] = weekend_busy.node_trip.str.split("-", expand=True)
weekend_busy.head()
for line in weekend_busy.iterrows():
    weekend_busy_G.add_edge(line[1]['source'], line[1]['dest'], weight=line[1]['time_taken'])

In [34]:
weekend_normal_G = nx.Graph()
weekend_normal = pd.read_csv('processed_csv/weekend_geohash_normal_6.csv')
weekend_normal = weekend_normal.groupby('node_trip').max().reset_index()
weekend_normal[['source', 'dest']] = weekend_normal.node_trip.str.split("-", expand=True)
for line in weekend_normal.iterrows():
    weekend_normal_G.add_edge(line[1]['source'], line[1]['dest'], weight=line[1]['time_taken'])

In [35]:
weekday_busy_G = nx.Graph()
weekday_busy = pd.read_csv('processed_csv/weekday_geohash_busy_6.csv')
weekday_busy = weekday_busy.groupby('node_trip').max().reset_index()
weekday_busy[['source', 'dest']] = weekday_busy.node_trip.str.split("-", expand=True)
for line in weekday_busy.iterrows():
    weekday_busy_G.add_edge(line[1]['source'], line[1]['dest'], weight=line[1]['time_taken'])

In [36]:
weekday_normal_G = nx.Graph()
weekday_normal = pd.read_csv('processed_csv/weekday_geohash_normal_6.csv')
weekday_normal = weekday_normal.groupby('node_trip').max().reset_index()
weekday_normal[['source', 'dest']] = weekday_normal.node_trip.str.split("-", expand=True)
for line in weekday_normal.iterrows():
    weekday_normal_G.add_edge(line[1]['source'], line[1]['dest'], weight=line[1]['time_taken'])

In [37]:
main_graph_G = nx.Graph()
main_df = pd.concat([weekend_busy, weekend_normal, weekday_busy, weekday_normal])
main_df = main_df.groupby('node_trip').max().reset_index()
main_df[['source', 'dest']] = main_df.node_trip.str.split("-", expand=True)
for line in main_df.iterrows():
    main_graph_G.add_edge(line[1]['source'], line[1]['dest'], weight=line[1]['time_taken'])

In [38]:
## Simple testing
test = pd.read_csv('processed_csv/test_set.csv')

# Comment the following lines if not using 6
test['geohash_source'] = test['geohash_source'].astype(str).str[:6]
test['geohash_dest'] = test['geohash_dest'].astype(str).str[:6]
test.tail(5)

,trj_id,source_lat,source_lng,source_timestamp,dest_lat,dest_lng,dest_timestamp,time_taken,geohash_source,geohash_dest,hour,day
4195,9843,1.311328,103.844514,2019-04-08 05:32:20,1.421571,103.796251,2019-04-08 05:46:10,830.0,w21z7n,w23b1f,5,0
4196,9856,1.375002,103.877892,2019-04-14 00:49:40,1.299927,103.801498,2019-04-14 01:08:33,1133.0,w21zgf,w21z6h,0,6
4197,988,1.435788,103.802898,2019-04-14 05:10:53,1.327159,103.827138,2019-04-14 05:29:32,1119.0,w23b4j,w21zd9,5,6
4198,9922,1.339792,103.695191,2019-04-18 10:42:31,1.298305,103.853856,2019-04-18 11:40:25,3474.0,w21xxe,w21z7k,10,3
4199,9930,1.346563,103.742625,2019-04-19 09:02:31,1.340791,103.981419,2019-04-19 09:30:54,1703.0,w21z8t,w21zwh,9,4

In [27]:
len(unique(test['trj_id']))

4200

In [28]:
test['time_taken'].mean()

1246.4185714285713

In [109]:
busy_hours = [7, 8, 9, 17, 18, 19]
weekend_num = [5, 6]
accuracy_arr = []
for test_case in test.iterrows():
    temp_arr = []
    rain_weight = 0
    poi_weight = 0
    maxspeed_weight = 0
    rain_bool = apr_weather.loc[(apr_weather['day'] == test_case[1]['day'] )& (apr_weather['hour'] == test_case[1]['hour'])]['rain']
    if rain_bool is True:
        rain_weight = 0.15
    try:
        if test_case[1]['hour'] in busy_hours and test_case[1]['day'] in weekend_num:
            path = nx.dijkstra_path(weekend_busy_G,source=test_case[1]['geohash_source'], target=test_case[1]['geohash_dest'], weight='weight')
            total_weight = 0
            for i in range(len(path) - 1):
                poi_num = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['no_poi']
                max_speed = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['maxspeed']
                if len(poi_num) > 0 and poi_num > 5:
                    poi_weight = 0.15
                if len(max_speed) > 0 and max_speed > 50:
                    maxspeed_weight = 0.15
                total_weight += weekend_busy_G[path[i]][path[i+1]]['weight'] * (1 + rain_weight + poi_weight + maxspeed_weight)
            temp_arr.append(test_case[1]['trj_id'])
            temp_arr.append(test_case[1]['time_taken'])
            temp_arr.append(total_weight)
            accuracy_arr.append(temp_arr)

        elif test_case[1]['hour'] not in busy_hours and test_case[1]['day'] in weekend_num:
            path = nx.dijkstra_path(weekend_normal_G,source=test_case[1]['geohash_source'], target=test_case[1]['geohash_dest'], weight='weight')
            total_weight = 0
            for i in range(len(path) - 1):
                poi_num = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['no_poi']
                max_speed = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['maxspeed']
                if len(poi_num) > 0 and poi_num > 5:
                    poi_weight = 0.15
                if len(max_speed) > 0 and max_speed > 50:
                    maxspeed_weight = 0.15
                total_weight += weekend_normal_G[path[i]][path[i+1]]['weight'] * (1 + rain_weight + poi_weight + maxspeed_weight)
            temp_arr.append(test_case[1]['trj_id'])
            temp_arr.append(test_case[1]['time_taken'])
            temp_arr.append(total_weight)
            accuracy_arr.append(temp_arr)

        elif test_case[1]['hour'] in busy_hours and test_case[1]['day'] not in weekend_num:
            path = nx.dijkstra_path(weekday_busy_G,source=test_case[1]['geohash_source'], target=test_case[1]['geohash_dest'], weight='weight')
            total_weight = 0
            for i in range(len(path) - 1):
                poi_num = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['no_poi']
                max_speed = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['maxspeed']
                if len(poi_num) > 0 and poi_num > 5:
                    poi_weight = 0.15
                if len(max_speed) > 0 and max_speed > 50:
                    maxspeed_weight = 0.15
                total_weight += weekday_busy_G[path[i]][path[i+1]]['weight'] * (1 + rain_weight + poi_weight + maxspeed_weight)
            temp_arr.append(test_case[1]['trj_id'])
            temp_arr.append(test_case[1]['time_taken'])
            temp_arr.append(total_weight)
            accuracy_arr.append(temp_arr)

        elif test_case[1]['hour'] not in busy_hours and test_case[1]['day'] not in weekend_num:
            path = nx.dijkstra_path(weekday_normal_G,source=test_case[1]['geohash_source'], target=test_case[1]['geohash_dest'], weight='weight')
            total_weight = 0
            for i in range(len(path) - 1):
                poi_num = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['no_poi']
                max_speed = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['maxspeed']
                if len(poi_num) > 0 and poi_num > 5:
                    poi_weight = 0.15
                if len(max_speed) > 0 and max_speed > 50:
                    maxspeed_weight = 0.15
                total_weight += weekday_normal_G[path[i]][path[i+1]]['weight'] * (1 + rain_weight + poi_weight + maxspeed_weight)
            temp_arr.append(test_case[1]['trj_id'])
            temp_arr.append(test_case[1]['time_taken'])
            temp_arr.append(total_weight)
            accuracy_arr.append(temp_arr)
    except:

        try:
            path = nx.dijkstra_path(main_graph_G,source=test_case[1]['geohash_source'], target=test_case[1]['geohash_dest'], weight='weight')
            total_weight = 0
            for i in range(len(path) - 1):
                poi_num = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['no_poi']
                max_speed = sg_geofabrik.loc[sg_geofabrik['geohash'] == path[i]]['maxspeed']
                if len(poi_num) > 0 and poi_num > 5:
                    poi_weight = 0.15
                if len(max_speed) > 0 and max_speed > 50:
                    maxspeed_weight = 0.15
                total_weight += main_graph_G[path[i]][path[i+1]]['weight'] * (1 + rain_weight + poi_weight + maxspeed_weight)
            temp_arr.append(test_case[1]['trj_id'])
            temp_arr.append(test_case[1]['time_taken'])
            temp_arr.append(total_weight)
            accuracy_arr.append(temp_arr)
        except:
            print('Error for' + str(test_case[1]['trj_id']))
            pass
            #temp_arr.append(test_case[1]['trj_id'])
            #temp_arr.append(test_case[1]['time_taken'])
            #temp_arr.append(1246.4185714285713)
            #accuracy_arr.append(temp_arr)

Error for50499
Error for74835

In [115]:
from sklearn.metrics import mean_squared_error
results = pd.DataFrame(accuracy_arr)
results.columns = ['trj_id', 'actual', 'predicted']
results['test_predicted_manual'] = results['predicted'] * 1.25
results_rmse = sqrt(mean_squared_error(results['actual'], results['predicted']))
results_rmse_manual = sqrt(mean_squared_error(results['actual'], results['test_predicted_manual']))

results.head(30)

    trj_id  actual  predicted  test_predicted_manual
0       10  1149.0      887.0                1108.75
1    10001  1250.0     1458.0                1822.50
2    10010  2349.0     1466.0                1832.50
3    10018  1507.0     1382.0                1727.50
4    10087  1054.0     1252.0                1565.00
5     1015  1585.0     2018.0                2522.50
6    10238   997.0     1315.0                1643.75
7    10245  1029.0     1373.0                1716.25
8    10278  1161.0     1134.0                1417.50
9    10284   818.0      953.0                1191.25
10     103  1271.0     1062.0                1327.50
11   10360  1539.0     1646.0                2057.50
12   10377  1182.0     1507.0                1883.75
13   10405  1106.0     1109.0                1386.25
14   10429  2415.0     2298.0                2872.50
15   10459  1274.0     1032.0                1290.00
16    1048  1901.0     1338.0                1672.50
17   10509  1325.0      999.0                1248.75
18    1051  1363.0     1590.0                1987.50
19   10510  1654.0     1747.0                2183.75
20   10567  1668.0     1808.0                2260.00
21   10576  1174.0     1071.0                1338.75
22   10582  1596.0     1309.0                1636.25
23   10597  1463.0     1343.0                1678.75
24   10626  1023.0     1466.0                1832.50
25   10627  1088.0      929.0                1161.25
26    1065  1069.0     1234.0                1542.50
27    1070  1273.0     1029.0                1286.25
28   10776  1165.0      627.0                 783.75
29    1080   990.0     1341.0                1676.25

In [116]:
print(len(results))
print(len(results[results.actual <= results.predicted]))
print(len(results[results.actual >= results.predicted]))

4198
2292
1914

In [117]:
print(results_rmse)
print(results_rmse_manual)

490.152296922273
684.3663057796908

In [ ]:
results.head(15)

In [ ]:
print(len(unique(test['trj_id'])))
print(len(unique(results['trj_id'])))

In [107]:
test.head()
test[test['trj_id']==10776]

,trj_id,source_lat,source_lng,source_timestamp,dest_lat,dest_lng,dest_timestamp,time_taken,geohash_source,geohash_dest,hour,day
28,10776,1.308287,103.771463,2019-04-15 00:32:08,1.301813,103.843097,2019-04-15 00:51:33,1165.0,w21z3q,w21z7h,0,0

In [53]:
weekend_normal = pd.read_csv('weekend_geohash_normal_6.csv')
weekend_normal = weekend_normal.groupby('node_trip').agg(['max','min']).reset_index()
weekend_normal.head()

       node_trip trj_id        geohash_source         geohash_dest          \
                    max    min            max     min          max     min
0  w21xjz-w21xjy  10452  10452         w21xjz  w21xjz       w21xjy  w21xjy
1  w21xmb-w21xjz  10452  10452         w21xmb  w21xmb       w21xjz  w21xjz
2  w21xmc-w21xmb  10452  10452         w21xmc  w21xmc       w21xmb  w21xmb
3  w21xmf-w21xq1  10452  10452         w21xmf  w21xmf       w21xq1  w21xq1
4  w21xmg-w21xmf  10452  10452         w21xmg  w21xmg       w21xmf  w21xmf

      timestamp_source                            timestamp_dest  \
                   max                  min                  max
0  2019-04-21 10:39:55  2019-04-21 10:39:55  2019-04-21 10:40:38
1  2019-04-21 10:38:41  2019-04-21 10:38:41  2019-04-21 10:40:04
2  2019-04-21 10:38:18  2019-04-21 10:38:18  2019-04-21 10:38:45
3  2019-04-21 10:37:13  2019-04-21 10:37:13  2019-04-21 10:38:06
4  2019-04-21 10:36:37  2019-04-21 10:36:37  2019-04-21 10:37:21

                       time_taken       hour     day
                   min        max   min  max min max min
0  2019-04-21 10:40:38       43.0  43.0   10  10   6   6
1  2019-04-21 10:40:04       83.0  83.0   10  10   6   6
2  2019-04-21 10:38:45       27.0  27.0   10  10   6   6
3  2019-04-21 10:38:06       53.0  53.0   10  10   6   6
4  2019-04-21 10:37:21       44.0  44.0   10  10   6   6

In [149]:
weekend_normal = pd.read_csv('weekend_geohash_normal.csv')
weekend_normal.head()

,trj_id,geohash_source,geohash_dest,timestamp_source,timestamp_dest,time_taken,hour,day,node_trip
0,10011,w21xx8v,w21xx8y,2019-04-20 08:06:26,2019-04-20 08:06:27,1.0,8,5,w21xx8v-w21xx8y
1,10011,w21xx8y,w21xx8z,2019-04-20 08:06:27,2019-04-20 08:06:37,10.0,8,5,w21xx8y-w21xx8z
2,10011,w21xx8z,w21xx8x,2019-04-20 08:06:37,2019-04-20 08:06:45,8.0,8,5,w21xx8z-w21xx8x
3,10011,w21xx8x,w21xxbb,2019-04-20 08:06:45,2019-04-20 08:06:46,1.0,8,5,w21xx8x-w21xxbb
4,10011,w21xxbb,w21xxb8,2019-04-20 08:06:46,2019-04-20 08:06:47,1.0,8,5,w21xxbb-w21xxb8

In [16]:
#nx.shortest_path_length(G,source='w21z6hb',target='w21zep1')
path = nx.dijkstra_path(weekday_normal_G,source='w21z7n9',target='w23b1fy', weight='weight')
print(path)
total_weight = 0
for i in range(len(path) - 1):
    total_weight += weekday_normal_G[path[i]][path[i+1]]['weight']
print(total_weight)

['w21z7n9', 'w21z7p6', 'w21ze0n', 'w21ze22', 'w21ze29', 'w21ze2d', 'w21ze2g', 'w21ze3t', 'w21ze3v', 'w21ze6n', 'w21ze6y', 'w21ze7j', 'w21ze7t', 'w21zekm', 'w21zeku', 'w21zem5', 'w21zemh', 'w21zeme', 'w21zemd', 'w21zemf', 'w21zeq6', 'w21zeq3', 'w21zeq9', 'w21zeqd', 'w21zer6', 'w21zerg', 'w21zg2k', 'w21zg2s', 'w21zg2u', 'w21zg2v', 'w21zg3m', 'w21zg6g', 'w21zg75', 'w21zg7g', 'w21zgk5', 'w21zgm7', 'w21zgq4', 'w21zgq3', 'w21zgnr', 'w21zgnq', 'w21zgnj', 'w21zgn6', 'w21zgn1', 'w21zgn2', 'w21zgn0', 'w21zfyj', 'w21zfvg', 'w21zfvc', 'w21zftw', 'w21zfts', 'w21zft9', 'w21zfmz', 'w21zfmy', 'w21zfmv', 'w21zfq7', 'w21zfqf', 'w21zfqc', 'w21zfr1', 'w21zfr3', 'w21zfr8', 'w23b40p', 'w23b40w', 'w23b41s', 'w23b441', 'w23b448', 'w23b1fx', 'w23b1fy']
1195.0

In [148]:
mean_squared_error(results['actual'], results['test_predicted_manual'])

378070.5397379378

In [151]:
print(len(weekend_normal))
print(len(unique(weekend_normal['node_trip'])))

205091
17909